from typing import Any, Dict

from asim.common.visualization.color.color import BLACK, ELLIS_5, LIGHT_GREY, NEW_TAB_10, TAB_10, Color
from asim.common.visualization.color.config import PlotConfig
from asim.dataset.maps.map_datatypes import MapSurfaceType
from asim.dataset.observation.detection.detection import TrafficLightStatus
from asim.dataset.observation.detection.detection_types import DetectionType

MAP_SURFACE_CONFIG: Dict[MapSurfaceType, PlotConfig] = {
    MapSurfaceType.LANE: PlotConfig(
        fill_color=LIGHT_GREY,
        fill_color_alpha=1.0,
        line_color=LIGHT_GREY,
        line_color_alpha=0.0,
        line_width=1.0,
        line_style="-",
        zorder=1,
    ),
    MapSurfaceType.LANE_GROUP: PlotConfig(
        fill_color=LIGHT_GREY,
        fill_color_alpha=1.0,
        line_color=LIGHT_GREY,
        line_color_alpha=0.0,
        line_width=1.0,
        line_style="-",
        zorder=1,
    ),
    MapSurfaceType.INTERSECTION: PlotConfig(
        fill_color=LIGHT_GREY,
        fill_color_alpha=1.0,
        line_color=LIGHT_GREY,
        line_color_alpha=0.0,
        line_width=1.0,
        line_style="-",
        zorder=1,
    ),
    MapSurfaceType.CROSSWALK: PlotConfig(
        fill_color=Color("#c69fbb"),
        fill_color_alpha=1.0,
        line_color=Color("#c69fbb"),
        line_color_alpha=0.0,
        line_width=1.0,
        line_style="-",
        zorder=2,
    ),
    MapSurfaceType.WALKWAY: PlotConfig(
        fill_color=Color("#d4d19e"),
        fill_color_alpha=1.0,
        line_color=Color("#d4d19e"),
        line_color_alpha=0.0,
        line_width=1.0,
        line_style="-",
        zorder=1,
    ),
    MapSurfaceType.CARPARK: PlotConfig(
        fill_color=Color("#b9d3b4"),
        fill_color_alpha=1.0,
        line_color=Color("#b9d3b4"),
        line_color_alpha=0.0,
        line_width=0.0,
        line_style="-",
        zorder=1,
    ),
    MapSurfaceType.GENERIC_DRIVABLE: PlotConfig(
        fill_color=LIGHT_GREY,
        fill_color_alpha=1.0,
        line_color=LIGHT_GREY,
        line_color_alpha=0.0,
        line_width=1.0,
        line_style="-",
        zorder=1,
    ),
}

BOX_DETECTION_CONFIG: Dict[DetectionType, Any] = {
    DetectionType.VEHICLE: {
        "fill_color": ELLIS_5[4],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 3,
    },
    DetectionType.PEDESTRIAN: {
        "fill_color": NEW_TAB_10[6],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 2,
    },
    DetectionType.BICYCLE: {
        "fill_color": ELLIS_5[3],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 2,
    },
    DetectionType.TRAFFIC_CONE: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    DetectionType.BARRIER: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    DetectionType.CZONE_SIGN: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    DetectionType.GENERIC_OBJECT: {
        "fill_color": NEW_TAB_10[5],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": None,
        "zorder": 2,
    },
    DetectionType.EGO: {
        "fill_color": ELLIS_5[0],
        "fill_color_alpha": 1.0,
        "line_color": BLACK,
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "-",
        "heading_style": "line",
        "zorder": 2,
    },
}

TRAFFIC_LIGHT_CONFIG: Dict[TrafficLightStatus, Any] = {
    TrafficLightStatus.RED: {
        "line_color": TAB_10[3],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
    TrafficLightStatus.YELLOW: {
        "line_color": TAB_10[1],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
    TrafficLightStatus.GREEN: {
        "line_color": TAB_10[2],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
    TrafficLightStatus.UNKNOWN: {
        "line_color": TAB_10[5],
        "line_color_alpha": 1.0,
        "line_width": 1.0,
        "line_style": "--",
        "zorder": 1,
    },
}

EGO_CONFIG: Dict[str, Any] = {
    "fill_color": ELLIS_5[0],
    "fill_color_alpha": 1.0,
    "line_color": BLACK,
    "line_color_alpha": 1.0,
    "line_width": 1.0,
    "line_style": "-",
    "heading_style": "line",
    "zorder": 3,
}

TRAJECTORY_CONFIG: Dict[str, Any] = {
    "human": {
        "fill_color": NEW_TAB_10[4],
        "fill_color_alpha": 1.0,
        "line_color": NEW_TAB_10[4],
        "line_color_alpha": 1.0,
        "line_width": 2.0,
        "line_style": "-",
        "marker": "o",
        "marker_size": 5,
        "marker_edge_color": BLACK,
        "zorder": 3,
    },
    "agent": {
        "fill_color": ELLIS_5[0],
        "fill_color_alpha": 1.0,
        "line_color": ELLIS_5[0],
        "line_color_alpha": 1.0,
        "line_width": 2.0,
        "line_style": "-",
        "marker": "o",
        "marker_size": 5,
        "marker_edge_color": BLACK,
        "zorder": 3,
    },
}
