defaults:
  - /dataset_converter_config@_global_: kitti360

_target_: py123d.parser.kitti360.kitti360_parser.Kitti360Parser
_convert_: 'all'

splits: ["kitti360_train", "kitti360_val", "kitti360_test"]

kitti360_data_root: ${dataset_paths.kitti360_data_root}

# NOTE: We preprocess detections into cache directory to speed up repeated conversions
# The bounding boxes are preprocessed into a per-frame format based on the ego distance and
# visibility based on the lidar point cloud.
detection_cache_root: ${dataset_paths.kitti360_data_root}/preprocessed_detections
detection_radius: 60.0

# NOTE: KITTI-360 does not have official splits, so we just put all sequences in the training set.
train_sequences:
  - "2013_05_28_drive_0000_sync"
  - "2013_05_28_drive_0002_sync"
  - "2013_05_28_drive_0003_sync"
  - "2013_05_28_drive_0004_sync"
  - "2013_05_28_drive_0005_sync"
  - "2013_05_28_drive_0006_sync"
  - "2013_05_28_drive_0007_sync"
  - "2013_05_28_drive_0009_sync"
  - "2013_05_28_drive_0010_sync"

val_sequences: []
test_sequences: []
