parser:
  _target_: py123d.parser.opendrive.opendrive_parser.OpenDriveParser
  _convert_: 'all'

  xodr_paths:
    - "Town01.xodr.gz"
    - "Town02.xodr.gz"
    - "Town03.xodr.gz"
    - "Town04.xodr.gz"
    - "Town05.xodr.gz"
    - "Town06.xodr.gz"
    - "Town07.xodr.gz"
    - "Town10HD.xodr.gz"
    - "Town11.xodr.gz"
    - "Town12.xodr.gz"
    - "Town13.xodr.gz"
    - "Town15.xodr.gz"

  location: null
  interpolation_step_size: 1.0
  connection_distance_threshold: 0.1
  internal_only: true

dataset_converter_config:
  _target_: py123d.parser.dataset_converter_config.DatasetConverterConfig
  _convert_: 'all'

  force_log_conversion: false
  force_map_conversion: ${force_map_conversion}

  # Map only
  include_map: true

  # No sensor data for OpenDRIVE
  include_ego: false
  include_box_detections: false
  include_pinhole_cameras: false
  include_fisheye_mei_cameras: false
  include_lidars: false
  include_traffic_lights: false
  include_scenario_tags: false
  include_route: false

  pinhole_camera_store_option: "path"
  lidar_store_option: "path"
  lidar_point_cloud_codec: null
  lidar_point_feature_codec: null

log_writer:
  _target_: py123d.api.scene.arrow.arrow_log_writer.ArrowLogWriter
  _convert_: 'all'
  dataset_converter_config: ${dataset.dataset_converter_config}
  logs_root: ${dataset_paths.py123d_logs_root}
  sensors_root: ${dataset_paths.py123d_sensors_root}
  ipc_compression: null
  ipc_compression_level: null

map_writer:
  _target_: py123d.api.map.arrow.arrow_map_writer.ArrowMapWriter
  _convert_: 'all'
  force_map_conversion: ${force_map_conversion}
  maps_root: ${dataset_paths.py123d_maps_root}
  logs_root: ${dataset_paths.py123d_logs_root}
