import uuid
from typing import Final

# Fixed namespace UUID for all UUIDs generated by 123D, do not change!
UUID_NAMESPACE_123D: Final[uuid.UUID] = uuid.UUID("123D123D-123D-123D-123D-123D123D123D")


def create_deterministic_uuid(split: str, log_name: str, timestamp_us: int, misc: str = None) -> uuid.UUID:
    """Create a universally unique identifier (UUID) based on identifying fields.

    :param split: The data split (in the format {dataset_name}_{train, val, test})
    :param log_name: The name of the log without file extension
    :param timestamp_us: The timestamp in microseconds
    :param misc: Any additional information to include in the UUID, defaults to None
    :return: The generated deterministic UUID
    """
    # https://en.wikipedia.org/wiki/Universally_unique_identifier#Versions_3_and_5_(namespace_name-based)

    # Create a unique string from all identifying fields
    unique_string = f"{split}:{log_name}:{timestamp_us}"
    if misc:
        unique_string += f":{misc}"

    # Generate UUIDv5 (SHA-1 based, deterministic)
    return uuid.uuid5(UUID_NAMESPACE_123D, unique_string)
